spring:
  profiles:
    active: local
  application:
    name: health_butler

server:
  port: 8443
  servlet:
    context-path: /health_butler

logging:
  config: classpath:logback-spring.xml
  level:
    dao: debug
    org:
      mybatis: debug

